[theme]
primaryColor = "#1a73e8"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#e0e0e0"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS=false
port = 8501

[global]
title = "📊 BOM Data Quality Checker"
favicon = "https://example.com/logo.png"
